BEGIN;

ALTER TABLE ofertas
    ADD COLUMN IF NOT EXISTS area VARCHAR(100) NOT NULL DEFAULT 'General',
    ADD COLUMN IF NOT EXISTS requisitos TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS duracion VARCHAR(120),
    ADD COLUMN IF NOT EXISTS horario VARCHAR(120),
    ADD COLUMN IF NOT EXISTS contacto_email VARCHAR(254);

COMMIT;
